version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trialdb
    ports:
      - "3308:3306"

  app:
    build:
      context: ./app
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
